<div class="story">
    <h1 class="hero-header">Static Box Example</h1>
	<p>This is a example of static html webpage generated by WBengine->Box->render() function, located at: </p><p class="alert alert-info">{$About}</p>
    <p>The HTML template file for this box is located at "App/Src/View/" directory, organized by a section name. The filenames and directories should be named with first upper letter. The section names is also stored in database and also is customizable.</p>
    <p>All definitions about the boxes is stored in MySQL database in two tables "cms_boxes". There is stricted relation between all tables by unique key "site_id", located in all tables "cms_boxes", "cms_boxorders", "cms_sites", "cms_menu" and "cms_articles".</p>
    <p>The Box definition stored in table "cms_boxes" containing items "module" coresponding the PHP class name and "method" what coresponding the method name of this class.</p>
    <h4>About Box definition</h4>
    <p>Here is About box definition stored in table "cms_boxes" and related files and tei location:</p>
    <ul class="list-group">
        <li>"name" -> About box, for better organisation in backed for example</li>
        <li>"module" -> Articles -> must be existing php class located in /App/Src/Box/...</li>
        <li>"method" -> About -> must be existing method name in php class "Articles"</li>
        <li>"section_id" - 1 -> is central box related to table "cms_sections"</li>
        <li>"static" -> 1 -> indicate that is static html, so renderer class should skip parsing source code by defined Formater</li>
        <li>"shared" -> 0 -> this box will shown only on defined section, if value = 1, all other sites show this box too. (Great for rendering Adworsements, banners etc.)</li>
    </ul>
    <p>So, finaly We should have may boxes on single site or across all sites. For this example the HTML template file should be located at: <span class="mark">/App/Src/View/Front/Central/about.tpl</span></p>
</div>